apiVersion: v1
kind: Service
metadata:
  name: simple-time-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: simple-time
  type: LoadBalancer